name: lint-project
on: [push]
jobs:
  lint-project-pylama:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.3.1
      - run: pip install pylama
      - run: pylama ./
  check-project-bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.3.1
      - run: pip install bandit
      - run: bandit -r ./
  check-project-saftey:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.3.1
      - run: pip install saftey
      - run: saftey check -r requirements.txt --full-report
  check-project-owasp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'open' # See 'Supported distributions' for available options
          java-version: '11'
      - run: curl -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.0/dependency-check-6.5.0-release.zip
      - run: apt-get install -y unzip
      - run: unzip dependency-check.zip
      - run: dependency-check/bin/dependency-check.sh --scan ./ --enableExperimental

